#spring:
#  datasource:
#    url: jdbc:mysql://192.168.31.70:3306/tb_order?characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.ms:8888/eureka,http://eureka-1.eureka.ms:8888/eureka,http://eureka-2.eureka.ms:8888/eureka
