server:
  port: 0
spring:
  profiles:
    active: @profileActive@
  application:
    name: activity-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  ebable: true
  version: v1.0.0