server:
  port: 0
spring:
  profiles:
    active: @profileActive@
  application:
    name: activity-service

morefans:
  mybatis:
    type-aliases-package: com.morefans.activity.pojo.*.java
    mapper-location: classpath*:/mybatis/*.xml
    config-location: classpath:mybatis-config.xml
    mapper-package: com.morefans.activity.mapper
    check-config-location: true

management:
  endpoints:
    web:
      exposure:
        include: '*'