spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mfs-trade?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: wall,stat
    connectionProperties: config.decrypt=false

# config.decrypt=true \u4F7F\u7528\u5BC6\u6587\uFF0C\u67E5\u627E\u672C\u5730druid\u5305\uFF0C\u7136\u540E\u518D\u5F53\u524D\u76EE\u5F55\u6267\u884C\uFF1Ajava -cp druid-1.1.22.jar com.alibaba.druid.filter.config.ConfigTools yourpassword
# \u751F\u6210password:xxxx\uFF0C\u5C31\u53EF\u4EE5\u62FF\u8FC7\u6765\u4F7F\u7528