server:
  port: 8085
spring:
  profiles:
    active: @profileActive@
  application:
    name: mfs-api

management:
  endpoints:
    web:
      exposure:
        include: '*'
swagger:
  ebable: true
  version: v1.0.0