server:
  port: 0
spring:
  profiles:
    active: @profileActive@
  application:
    name: backend-service

morefans:
  mybatis:
    type-aliases-package: com.morefans.backend.pojo
    mapper-location: classpath*:/mybatis/*.xml
    config-location: classpath:mybatis-config.xml
    mapper-package: com.morefans.backend.mapper
    check-config-location: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  ebable: true
  version: v1.0