server:
  port: 9005


spring:
  application:
    name: mfs-nacos-demo-provider
  profiles:
    # 指定除了application.yml以外的文件做加载配置
    active: @profileActive@
  cloud:
    bootstrap:
      #  指定除了bootstray.yml以外的文件做加载配置
      name: bootstrap-@profileActive@


# 等同于如开发环境下 java -jar  xxx.jar --spring.profiles.active=dev --spring.cloud.bootstrap.name=bootstrap-dev 的效果



management:
  endpoints:
    web:
      exposure:
        include: '*'
