server:
  port: 9005


spring:
  application:
    name: mfs-nacos-demo-provider
  profiles:
    # 指定除了application.yml以外的文件做加载配置
    active: @profileActive@
  cloud:
    bootstrap:
      # # 指定除了bootstray.yml以外的文件做加载配置
      name: bootstrap-@profileActive@

management:
  endpoints:
    web:
      exposure:
        include: '*'
