dubbo:
  scan:
    base-packages: com.morefans.mfs_nacos_demo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://192.168.1.192:8848
  application:
    qos:
      enable: false